import datetime
from typing import List

from flask_login import UserMixin
from peewee import (
    DateTimeField,
    CharField,
    FloatField,
    ForeignKeyField,
    AutoField,
    BooleanField,
    TextField,
    DateField,
    BigIntegerField,
    IntegerField,
)

from apps.common.db import BaseModel


def seed(model, seed_list: List[dict], truncate: bool = True):
    if truncate:
        model.delete()
    model.bulk_create([model(**item) for item in seed_list])


class User(BaseModel, UserMixin):
    id = AutoField()
    username = CharField(unique=True, max_length=50, null=False)
    email = CharField(unique=True, max_length=50, null=False)
    password = CharField(max_length=80, null=False)
    status = BooleanField(default=True, null=True)
    created_at = DateTimeField(default=datetime.datetime.now, null=True)

    class Meta:
        table_name = "user"


class Machine(BaseModel):
    id = AutoField()
    machine_name = CharField(max_length=50, unique=True, null=False)
    equipment_id = CharField(max_length=50, unique=True, null=False)
    company_name = CharField(max_length=50, null=False)
    created_at = DateTimeField(default=datetime.datetime.now, null=True)

    class Meta:
        table_name = "machine"


class DumpInfo(BaseModel):
    id = AutoField()
    filename = CharField(max_length=50, unique=True)
    load_date = DateField()
    machine_id = ForeignKeyField(Machine, backref="machinedump", null=False)
    created_at = DateTimeField(default=datetime.datetime.now, null=True)

    class Meta:
        table_name = "dump_info"


class MachineData(BaseModel):
    id = AutoField()
    timestamp = DateTimeField(null=False)
    machine_id = ForeignKeyField(Machine, backref="machinedata", null=False)
    winding_act_press = FloatField(null=True)
    penning_act_press = FloatField(null=True)
    baratron_act_press = FloatField(null=True)
    bp1_water_flow = FloatField(null=True)
    bp2_water_flow = FloatField(null=True)
    bp3_water_flow = FloatField(null=True)
    bp4_water_flow = FloatField(null=True)
    bp5_water_flow = FloatField(null=True)
    bp6_water_flow = FloatField(null=True)
    bp7_water_flow = FloatField(null=True)
    bp8_water_flow = FloatField(null=True)
    bp1_water_temp = FloatField(null=True)
    bp2_water_temp = FloatField(null=True)
    bp3_water_temp = FloatField(null=True)
    bp4_water_temp = FloatField(null=True)
    bp5_water_temp = FloatField(null=True)
    bp6_water_temp = FloatField(null=True)
    bp7_water_temp = FloatField(null=True)
    bp8_water_temp = FloatField(null=True)
    dp1_press = FloatField(null=True)
    dp2_press = FloatField(null=True)
    dp3_press = FloatField(null=True)
    dp4_press = FloatField(null=True)
    dp1_temp = FloatField(null=True)
    dp2_temp = FloatField(null=True)
    dp3_temp = FloatField(null=True)
    dp4_temp = FloatField(null=True)
    rp1_cylinder_temp = FloatField(null=True)
    rp2_cylinder_temp = FloatField(null=True)
    rp4_cylinder_temp = FloatField(null=True)
    rp6_cylinder_temp = FloatField(null=True)
    rp8_cylinder_temp = FloatField(null=True)
    rp1_coolant_temp = FloatField(null=True)
    rp2_coolant_temp = FloatField(null=True)
    rp4_coolant_temp = FloatField(null=True)
    rp6_coolant_temp = FloatField(null=True)
    rp8_coolant_temp = FloatField(null=True)
    drum_temp = FloatField(null=True)
    drum_temp_sp = FloatField(null=True)
    drum_act_dr = FloatField(null=True)
    drum_set_dr = FloatField(null=True)
    drum_act_tq = FloatField(null=True)
    drum_set_tq = FloatField(null=True)
    dtr1_act_dr = FloatField(null=True)
    dtr1_set_dr = FloatField(null=True)
    dtr1_act_tq = FloatField(null=True)
    dtr1_set_tq = FloatField(null=True)
    dtr1_act_current = FloatField(null=True)
    dtr1_chiller_temp = FloatField(null=True)
    dtr2_act_tq = FloatField(null=True)
    dtr2_set_tq = FloatField(null=True)
    dtr2_act_dr = FloatField(null=True)
    dtr2_set_dr = FloatField(null=True)
    dtr2_act_current = FloatField(null=True)
    gas_wedge_centre_sp = FloatField(null=True)
    gas_wedge_edge_sp = FloatField(null=True)
    gas_wedge_centre = FloatField(null=True)
    gas_wedge_edge = FloatField(null=True)
    gas_flow_set = FloatField(null=True)
    rew_wedge_centre_sp = FloatField(null=True)
    rew_wedge_edge_sp = FloatField(null=True)
    rew_wedge_centre = FloatField(null=True)
    rew_wedge_edge = FloatField(null=True)
    rew_act_tens = FloatField(null=True)
    rew_set_tens = FloatField(null=True)
    unw_act_tens = FloatField(null=True)
    unw_set_tens = FloatField(null=True)
    unw_dia = FloatField(null=True)
    rew_dia = FloatField(null=True)
    gap_pos_act = FloatField(null=True)
    gap_pos_set = FloatField(null=True)
    gapu_pos_act = FloatField(null=True)
    gapu_pos_set = FloatField(null=True)
    layon_act_force = FloatField(null=True)
    layon_set_force = FloatField(null=True)
    layonu_act_force = FloatField(null=True)
    layonu_set_force = FloatField(null=True)
    main_feed_temp = FloatField(null=True)
    main_feed_press = FloatField(null=True)
    main_return_press = FloatField(null=True)
    mec_feed_press = FloatField(null=True)
    mec_return_press = FloatField(null=True)
    cg1_cryo_temp = FloatField(null=True)
    cg2_cryo_temp = FloatField(null=True)
    cg3_cryo_temp = FloatField(null=True)
    cg4_cryo_temp = FloatField(null=True)
    cg5_cryo_temp = FloatField(null=True)
    cg6_cryo_temp = FloatField(null=True)
    cg7_cryo_temp = FloatField(null=True)
    cg8_cryo_temp = FloatField(null=True)
    pretrtr_arc_counter = FloatField(null=True)
    pretrtr_baratron = FloatField(null=True)
    pretrtr_tot_act_flw = FloatField(null=True)
    pretrtr_flow_plate = FloatField(null=True)
    pretrtr_flow_elec = FloatField(null=True)
    pretrtr_act_pwr = FloatField(null=True)
    pretrtr_set_pwr = FloatField(null=True)
    pretrtr_ar_act_flow = FloatField(null=True)
    pretrtr_o2_act_flow = FloatField(null=True)
    pretrtr_n2_act_flow = FloatField(null=True)
    pretrtr_ar_percent_sp = FloatField(null=True)
    pretrtr_o2_percent_sp = FloatField(null=True)
    pretrtr_n2_percent_sp = FloatField(null=True)
    posttrtr_arc_counter = FloatField(null=True)
    posttrtr_baratron = FloatField(null=True)
    posttrtr_tot_act_flw = FloatField(null=True)
    posttrtr_flow_plate = FloatField(null=True)
    posttrtr_flow_elec = FloatField(null=True)
    posttrtr_act_pwr = FloatField(null=True)
    posttrtr_set_pwr = FloatField(null=True)
    posttrtr_ar_act_flow = FloatField(null=True)
    posttrtr_o2_act_flow = FloatField(null=True)
    posttrtr_n2_act_flow = FloatField(null=True)
    posttrtr_ar_percent_sp = FloatField(null=True)
    posttrtr_o2_percent_sp = FloatField(null=True)
    posttrtr_n2_percent_sp = FloatField(null=True)
    shield_water_flow = FloatField(null=True)
    shutter_water_flow = FloatField(null=True)
    source_water_flow = FloatField(null=True)
    shield_water_temp = FloatField(null=True)
    shutter_water_temp = FloatField(null=True)
    source_water_temp = FloatField(null=True)
    spread_act_pos = FloatField(null=True)
    spread_set = FloatField(null=True)
    spread2_act_pos = FloatField(null=True)
    spread2_set = FloatField(null=True)
    spread3_act_pos = FloatField(null=True)
    spread3_set = FloatField(null=True)
    material_thickness = FloatField(null=True)
    first_probe = FloatField(null=True)
    last_probe = FloatField(null=True)
    first_boat = FloatField(null=True)
    last_boat = FloatField(null=True)
    monitor_num_in_use = FloatField(null=True)
    deposit_unit = FloatField(null=True)
    machine_power_usage = FloatField(null=True)
    machine_closed_kwh = FloatField(null=True)
    machine_open_kwh = FloatField(null=True)
    activemonitorreadings = TextField(null=True)
    boatpower = TextField(null=True)
    mfc_flow = TextField(null=True)
    mfc_flow2 = TextField(null=True)
    wirefeedrate = TextField(null=True)
    gas_flow_between_set = FloatField(null=True)
    average_deposit = FloatField(null=True)
    gre_highside_1 = FloatField(null=True)
    gre_lowside_1 = FloatField(null=True)
    gre_highside_2 = FloatField(null=True)
    gre_lowside_2 = FloatField(null=True)
    gre_glycol_prs = FloatField(null=True)
    gre_glycol_supply_tmp = FloatField(null=True)
    gre_tower_rtn_tmp = FloatField(null=True)
    gre_tower_supply_tmp = FloatField(null=True)
    gre_tower_flow_rate = FloatField(null=True)
    gre_superheat1 = FloatField(null=True)
    gre_superheat2 = FloatField(null=True)
    gre_exp_valve_pos1 = FloatField(null=True)
    gre_exp_valve_pos2 = FloatField(null=True)
    gre_cooling_demand = FloatField(null=True)
    gre_process_glycol_pump = BooleanField(null=True)
    gre_heater1 = BooleanField(null=True)
    gre_heater2 = BooleanField(null=True)
    gre_heater3 = BooleanField(null=True)
    gre_compressor1 = BooleanField(null=True)
    gre_compressor2 = BooleanField(null=True)
    gre_compressor3 = BooleanField(null=True)
    gre_compressor4 = BooleanField(null=True)
    gre_heating_valve = BooleanField(null=True)
    gre_eev_c1_status = BooleanField(null=True)
    gre_eev_c2_status = BooleanField(null=True)
    gre_dp_copy = BooleanField(null=True)
    gre_compressor5 = BooleanField(null=True)
    gre_compressor6 = BooleanField(null=True)
    gre_heater4 = BooleanField(null=True)
    gre_watchdog_status = BooleanField(null=True)
    gre_reversing_valve_status = BooleanField(null=True)
    avg_power = FloatField(null=True)
    varibow_height = FloatField(null=True)
    varibow_height_sp = FloatField(null=True)
    unwind_oscillation = FloatField(null=True)
    rewind_oscillation = FloatField(null=True)
    drum_speed_error = FloatField(null=True)
    dtr1_speed_error = FloatField(null=True)
    dtr2_speed_error = FloatField(null=True)
    unwind_motor_temp = FloatField(null=True)
    rewind_motor_temp = FloatField(null=True)
    drum_motor_temp = FloatField(null=True)
    dtr1_motor_temp = FloatField(null=True)
    dtr2_motor_temp = FloatField(null=True)
    draw_motor_temp = FloatField(null=True)
    ph_small_sp = FloatField(null=True)
    ph_medium_sp = FloatField(null=True)
    ph_large_sp = FloatField(null=True)
    ph_scratch_sp = FloatField(null=True)
    ph_density_small = FloatField(null=True)
    ph_density_medium = FloatField(null=True)
    ph_density_large = FloatField(null=True)
    ph_density_scratch = FloatField(null=True)
    cg1_suction_press = FloatField(null=True)
    cg2_suction_press = FloatField(null=True)
    cg3_suction_press = FloatField(null=True)
    cg4_suction_press = FloatField(null=True)
    cg5_suction_press = FloatField(null=True)
    cg6_suction_press = FloatField(null=True)
    cg7_suction_press = FloatField(null=True)
    cg8_suction_press = FloatField(null=True)
    cg1_discharge_press = FloatField(null=True)
    cg2_discharge_press = FloatField(null=True)
    cg3_discharge_press = FloatField(null=True)
    cg4_discharge_press = FloatField(null=True)
    cg5_discharge_press = FloatField(null=True)
    cg6_discharge_press = FloatField(null=True)
    cg7_discharge_press = FloatField(null=True)
    cg8_discharge_press = FloatField(null=True)
    cg1_coldest_liquid_temp = FloatField(null=True)
    cg2_coldest_liquid_temp = FloatField(null=True)
    cg3_coldest_liquid_temp = FloatField(null=True)
    cg4_coldest_liquid_temp = FloatField(null=True)
    cg5_coldest_liquid_temp = FloatField(null=True)
    cg6_coldest_liquid_temp = FloatField(null=True)
    cg7_coldest_liquid_temp = FloatField(null=True)
    cg8_coldest_liquid_temp = FloatField(null=True)
    rp1_7210_bearing = FloatField(null=True)
    rp1_6310_bearing = FloatField(null=True)
    rp1_7310_bearing = FloatField(null=True)
    rp1_7207_bearing = FloatField(null=True)
    rp1_unbalance = FloatField(null=True)
    rp1_looseness = FloatField(null=True)
    rp2_7210_bearing = FloatField(null=True)
    rp2_6310_bearing = FloatField(null=True)
    rp2_7310_bearing = FloatField(null=True)
    rp2_7207_bearing = FloatField(null=True)
    rp2_unbalance = FloatField(null=True)
    rp2_looseness = FloatField(null=True)
    rp4_7210_bearing = FloatField(null=True)
    rp4_6310_bearing = FloatField(null=True)
    rp4_7310_bearing = FloatField(null=True)
    rp4_7207_bearing = FloatField(null=True)
    rp4_unbalance = FloatField(null=True)
    rp4_looseness = FloatField(null=True)
    rp6_7210_bearing = FloatField(null=True)
    rp6_6310_bearing = FloatField(null=True)
    rp6_7310_bearing = FloatField(null=True)
    rp6_7207_bearing = FloatField(null=True)
    rp6_unbalance = FloatField(null=True)
    rp6_looseness = FloatField(null=True)
    rp8_7210_bearing = FloatField(null=True)
    rp8_6310_bearing = FloatField(null=True)
    rp8_7310_bearing = FloatField(null=True)
    rp8_7207_bearing = FloatField(null=True)
    rp8_unbalance = FloatField(null=True)
    rp8_looseness = FloatField(null=True)
    drum_draw_mode = BooleanField(null=True)
    dtr1_draw_mode = BooleanField(null=True)
    dtr2_draw_mode = BooleanField(null=True)
    vv1_open = BooleanField(null=True)
    vv1b_open = BooleanField(null=True)
    vv2_open = BooleanField(null=True)
    vv2b_open = BooleanField(null=True)
    vv2c_open = BooleanField(null=True)
    vv4_open = BooleanField(null=True)
    vv6a_open = BooleanField(null=True)
    vv6b_open = BooleanField(null=True)
    vv6c_open = BooleanField(null=True)
    vv7a_open = BooleanField(null=True)
    vv7b_open = BooleanField(null=True)
    vv7c_open = BooleanField(null=True)
    vv10b_open = BooleanField(null=True)
    vv10c_open = BooleanField(null=True)
    vv10d_open = BooleanField(null=True)
    vv11_open = BooleanField(null=True)
    vv12_open = BooleanField(null=True)
    shutter_open = BooleanField(null=True)
    shutter_closed = BooleanField(null=True)
    web_act_speed = FloatField(null=True)
    web_length = FloatField(null=True)
    web_speed_sp = FloatField(null=True)
    web_width = FloatField(null=True)
    wind_act_press = FloatField(null=True)
    wire_spd_set = FloatField(null=True)
    foreline_act_press = FloatField(null=True)
    src_water_flow = FloatField(null=True)
    totalinputlength = BigIntegerField(null=True)
    totaloutputbadlength = BigIntegerField(null=True)
    totaloutputgoodlength = BigIntegerField(null=True)
    rollinputlength = BigIntegerField(null=True)
    rolloutputbadlength = BigIntegerField(null=True)
    rolloutputgoodlength = BigIntegerField(null=True)
    penn_act_press = FloatField(null=True)
    max_machine_spd = FloatField(null=True)
    machine_running_time = BigIntegerField(null=True)
    machine_production_time = BigIntegerField(null=True)
    machine_online_time = BigIntegerField(null=True)
    fore_act_press = FloatField(null=True)
    downtime_operator_codes = CharField(null=True)
    downtime_machine_states = CharField(null=True)
    downtime_alarms = CharField(null=True)
    bar_act_press = FloatField(null=True)
    avg_power = FloatField(null=True)
    average_deposit = FloatField(null=True)
    created_at = DateTimeField(default=datetime.datetime.now, null=True)

    class Meta:
        table_name = "machine_data"


class Category(BaseModel):
    """_Create a categories class and assigned the table fields_

    Args:
        BaseModel (_type_): _description_
    """

    id = AutoField()
    name = CharField(unique=True, max_length=50, null=False)
    created_at = DateTimeField(default=datetime.datetime.now, null=True)

    class Meta:
        table_name = "category"


class SubCategory(BaseModel):
    """_Create a sub categories class and assigned the table fields_

    Args:
        BaseModel (_type_): _description_
    """

    id = AutoField()
    category_id = ForeignKeyField(Category, backref="subcategories", null=False)
    name = CharField(unique=True, max_length=100, null=False)
    variable_name = CharField(unique=True, max_length=100, null=False)
    unit = CharField(max_length=50, null=True)
    mini_limit = FloatField(null=True)
    maxi_limit = FloatField(null=True)
    created_at = DateTimeField(default=datetime.datetime.now, null=True)

    class Meta:
        table_name = "sub_category"
