[mypy]
python_version = 3.11
strict = False

# Ignore types for following packages as they miss typings
[mypy-defusedxml.*]
ignore_missing_imports = True

[mypy-botocore.vendored.*]
ignore_missing_imports = True

[mypy-moto]
ignore_missing_imports = True

